
// This file is AUTOGENERATED.
// Modify `tools/gen_classes.ers` if changes are needed to
// PCI device classes or the file format

#[allow(non_camel_case_types)]
#[derive(Copy, Clone, Eq, PartialEq, Hash)]
#[cfg_attr(feature = "pci_interface_func_debug_strings", derive(Debug))]
/// Represent a PCI interface function as an enumeration, for easier
/// matching with known valid values.
///
/// See PCI documentation or <https://wiki.osdev.org/PCI#Class_Codes>
/// for possible values.
pub enum PciDeviceInterfaceFunc {
    /// Enumeration matching device class 00h, subclass 00h, interface function 00h.
    Unclassified_Generic_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 00h, subclass 00h.
    Unclassified_Generic_Unknown(u8),
    /// Enumeration matching device class 00h, subclass 01h, interface function 00h.
    Unclassified_VgaCompatible_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 00h, subclass 01h.
    Unclassified_VgaCompatible_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 00h.
    Unclassified_Unknown(u8, u8),
    /// Enumeration matching device class 01h, subclass 00h, interface function 00h.
    MassStorageController_Scsi_VendorSpecific,
    /// Enumeration matching device class 01h, subclass 00h, interface function 11h.
    MassStorageController_Scsi_StorageDevice,
    /// Enumeration matching device class 01h, subclass 00h, interface function 12h.
    MassStorageController_Scsi_HostBusAdapter,
    /// Enumeration matching device class 01h, subclass 00h, interface function 13h.
    MassStorageController_Scsi_StorageDeviceAndController,
    /// Enumeration matching device class 01h, subclass 00h, interface function 21h.
    MassStorageController_Scsi_StorageDeviceOverPciE,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 00h.
    MassStorageController_Scsi_Unknown(u8),
    /// Enumeration matching all interface functions of device class 01h, subclass 01h.
    MassStorageController_Ide_AtaInterface(u8),
    /// Enumeration matching device class 01h, subclass 02h, interface function 00h.
    MassStorageController_FloppyDisk_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 02h.
    MassStorageController_FloppyDisk_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 03h, interface function 00h.
    MassStorageController_IpiBus_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 03h.
    MassStorageController_IpiBus_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 04h, interface function 00h.
    MassStorageController_Raid_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 04h.
    MassStorageController_Raid_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 05h, interface function 20h.
    MassStorageController_AtaWithAdma_SingleStepping,
    /// Enumeration matching device class 01h, subclass 05h, interface function 30h.
    MassStorageController_AtaWithAdma_ContinuousOperation,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 05h.
    MassStorageController_AtaWithAdma_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 06h, interface function 00h.
    MassStorageController_SerialAta_VendorSpecific,
    /// Enumeration matching device class 01h, subclass 06h, interface function 01h.
    MassStorageController_SerialAta_Ahci,
    /// Enumeration matching device class 01h, subclass 06h, interface function 02h.
    MassStorageController_SerialAta_SerialStorageBus,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 06h.
    MassStorageController_SerialAta_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 07h, interface function 00h.
    MassStorageController_SerialAttachedScsi_VendorSpecific,
    /// Enumeration matching device class 01h, subclass 07h, interface function 01h.
    MassStorageController_SerialAttachedScsi_Obsolete,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 07h.
    MassStorageController_SerialAttachedScsi_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 08h, interface function 00h.
    MassStorageController_NonVolatileMemory_VendorSpecific,
    /// Enumeration matching device class 01h, subclass 08h, interface function 01h.
    MassStorageController_NonVolatileMemory_NvmHci,
    /// Enumeration matching device class 01h, subclass 08h, interface function 02h.
    MassStorageController_NonVolatileMemory_NVMeIoController,
    /// Enumeration matching device class 01h, subclass 08h, interface function 03h.
    MassStorageController_NonVolatileMemory_NVMeAdministrativeController,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 08h.
    MassStorageController_NonVolatileMemory_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 09h, interface function 00h.
    MassStorageController_UniversalFlashStorage_VendorSpecific,
    /// Enumeration matching device class 01h, subclass 09h, interface function 01h.
    MassStorageController_UniversalFlashStorage_UfsHci,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 09h.
    MassStorageController_UniversalFlashStorage_Unknown(u8),
    /// Enumeration matching device class 01h, subclass 80h, interface function 00h.
    MassStorageController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 01h, subclass 80h.
    MassStorageController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 01h.
    MassStorageController_Unknown(u8, u8),
    /// Enumeration matching device class 02h, subclass 00h, interface function 00h.
    NetworkController_Ethernet_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 00h.
    NetworkController_Ethernet_Unknown(u8),
    /// Enumeration matching device class 02h, subclass 01h, interface function 00h.
    NetworkController_TokenRing_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 01h.
    NetworkController_TokenRing_Unknown(u8),
    /// Enumeration matching device class 02h, subclass 02h, interface function 00h.
    NetworkController_Fddi_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 02h.
    NetworkController_Fddi_Unknown(u8),
    /// Enumeration matching device class 02h, subclass 03h, interface function 00h.
    NetworkController_Atm_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 03h.
    NetworkController_Atm_Unknown(u8),
    /// Enumeration matching device class 02h, subclass 04h, interface function 00h.
    NetworkController_Isdn_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 04h.
    NetworkController_Isdn_Unknown(u8),
    /// Enumeration matching device class 02h, subclass 05h, interface function 00h.
    NetworkController_WorldFip_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 05h.
    NetworkController_WorldFip_Unknown(u8),
    /// Enumeration matching all interface functions of device class 02h, subclass 06h.
    NetworkController_PicMg214MultiComputing_PicMg(u8),
    /// Enumeration matching device class 02h, subclass 07h, interface function 00h.
    NetworkController_InfiniBand_Default,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 07h.
    NetworkController_InfiniBand_Unknown(u8),
    /// Enumeration matching device class 02h, subclass 80h, interface function 00h.
    NetworkController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 02h, subclass 80h.
    NetworkController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 02h.
    NetworkController_Unknown(u8, u8),
    /// Enumeration matching device class 03h, subclass 00h, interface function 00h.
    DisplayController_VgaCompatible_Vga,
    /// Enumeration matching device class 03h, subclass 00h, interface function 01h.
    DisplayController_VgaCompatible_Ibm8514,
    /// Enumeration matching unknown interface function values of device class 03h, subclass 00h.
    DisplayController_VgaCompatible_Unknown(u8),
    /// Enumeration matching device class 03h, subclass 01h, interface function 00h.
    DisplayController_Xga_Default,
    /// Enumeration matching unknown interface function values of device class 03h, subclass 01h.
    DisplayController_Xga_Unknown(u8),
    /// Enumeration matching device class 03h, subclass 02h, interface function 00h.
    DisplayController_NonVga3D_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 03h, subclass 02h.
    DisplayController_NonVga3D_Unknown(u8),
    /// Enumeration matching device class 03h, subclass 80h, interface function 00h.
    DisplayController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 03h, subclass 80h.
    DisplayController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 03h.
    DisplayController_Unknown(u8, u8),
    /// Enumeration matching device class 04h, subclass 00h, interface function 00h.
    MultimediaDevice_VideoDevice_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 04h, subclass 00h.
    MultimediaDevice_VideoDevice_Unknown(u8),
    /// Enumeration matching device class 04h, subclass 01h, interface function 00h.
    MultimediaDevice_AudioDevice_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 04h, subclass 01h.
    MultimediaDevice_AudioDevice_Unknown(u8),
    /// Enumeration matching device class 04h, subclass 02h, interface function 00h.
    MultimediaDevice_ComputerTelephony_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 04h, subclass 02h.
    MultimediaDevice_ComputerTelephony_Unknown(u8),
    /// Enumeration matching device class 04h, subclass 03h, interface function 00h.
    MultimediaDevice_HdaCompatible_HighDefinitionAudio,
    /// Enumeration matching device class 04h, subclass 03h, interface function 80h.
    MultimediaDevice_HdaCompatible_HighDefinitionAudioWithVendorExtension,
    /// Enumeration matching unknown interface function values of device class 04h, subclass 03h.
    MultimediaDevice_HdaCompatible_Unknown(u8),
    /// Enumeration matching device class 04h, subclass 80h, interface function 00h.
    MultimediaDevice_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 04h, subclass 80h.
    MultimediaDevice_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 04h.
    MultimediaDevice_Unknown(u8, u8),
    /// Enumeration matching device class 05h, subclass 00h, interface function 00h.
    MemoryController_Ram_Default,
    /// Enumeration matching unknown interface function values of device class 05h, subclass 00h.
    MemoryController_Ram_Unknown(u8),
    /// Enumeration matching device class 05h, subclass 01h, interface function 00h.
    MemoryController_Flash_Default,
    /// Enumeration matching unknown interface function values of device class 05h, subclass 01h.
    MemoryController_Flash_Unknown(u8),
    /// Enumeration matching device class 05h, subclass 02h, interface function 00h.
    MemoryController_CxlMemory_VendorSpecific,
    /// Enumeration matching device class 05h, subclass 02h, interface function 10h.
    MemoryController_CxlMemory_Cxl2Specifications,
    /// Enumeration matching unknown interface function values of device class 05h, subclass 02h.
    MemoryController_CxlMemory_Unknown(u8),
    /// Enumeration matching device class 05h, subclass 80h, interface function 00h.
    MemoryController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 05h, subclass 80h.
    MemoryController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 05h.
    MemoryController_Unknown(u8, u8),
    /// Enumeration matching device class 06h, subclass 00h, interface function 00h.
    Bridge_HostBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 00h.
    Bridge_HostBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 01h, interface function 00h.
    Bridge_IsaBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 01h.
    Bridge_IsaBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 02h, interface function 00h.
    Bridge_EisaBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 02h.
    Bridge_EisaBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 03h, interface function 00h.
    Bridge_McaBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 03h.
    Bridge_McaBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 04h, interface function 00h.
    Bridge_PciToPciBridge_PciToPci,
    /// Enumeration matching device class 06h, subclass 04h, interface function 01h.
    Bridge_PciToPciBridge_SubtractiveDecodePciToPci,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 04h.
    Bridge_PciToPciBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 05h, interface function 00h.
    Bridge_PcmciaBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 05h.
    Bridge_PcmciaBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 06h, interface function 00h.
    Bridge_NuBusBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 06h.
    Bridge_NuBusBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 07h, interface function 00h.
    Bridge_CardBusBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 07h.
    Bridge_CardBusBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 08h, interface function 00h.
    Bridge_RacewayBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 08h.
    Bridge_RacewayBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 09h, interface function 40h.
    Bridge_SemiTransparentPciToPciBridge_Primary,
    /// Enumeration matching device class 06h, subclass 09h, interface function 80h.
    Bridge_SemiTransparentPciToPciBridge_Secondary,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 09h.
    Bridge_SemiTransparentPciToPciBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 0Ah, interface function 00h.
    Bridge_InfiniBandtoPciHostBridge_Default,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 0Ah.
    Bridge_InfiniBandtoPciHostBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 0Bh, interface function 00h.
    Bridge_AdvancedSwitchingToPciHostBridge_VendorSpecific,
    /// Enumeration matching device class 06h, subclass 0Bh, interface function 01h.
    Bridge_AdvancedSwitchingToPciHostBridge_AsiSigInterface,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 0Bh.
    Bridge_AdvancedSwitchingToPciHostBridge_Unknown(u8),
    /// Enumeration matching device class 06h, subclass 80h, interface function 00h.
    Bridge_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 06h, subclass 80h.
    Bridge_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 06h.
    Bridge_Unknown(u8, u8),
    /// Enumeration matching device class 07h, subclass 00h, interface function 00h.
    CommunicationController_Serial_Uart8250,
    /// Enumeration matching device class 07h, subclass 00h, interface function 01h.
    CommunicationController_Serial_Uart16450,
    /// Enumeration matching device class 07h, subclass 00h, interface function 02h.
    CommunicationController_Serial_Uart16550,
    /// Enumeration matching device class 07h, subclass 00h, interface function 03h.
    CommunicationController_Serial_Uart16650,
    /// Enumeration matching device class 07h, subclass 00h, interface function 04h.
    CommunicationController_Serial_Uart16750,
    /// Enumeration matching device class 07h, subclass 00h, interface function 05h.
    CommunicationController_Serial_Uart16850,
    /// Enumeration matching device class 07h, subclass 00h, interface function 06h.
    CommunicationController_Serial_Uart16950,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 00h.
    CommunicationController_Serial_Unknown(u8),
    /// Enumeration matching device class 07h, subclass 01h, interface function 00h.
    CommunicationController_Parallel_ParallelPort,
    /// Enumeration matching device class 07h, subclass 01h, interface function 01h.
    CommunicationController_Parallel_BidirectionalParallelPort,
    /// Enumeration matching device class 07h, subclass 01h, interface function 02h.
    CommunicationController_Parallel_EcpParallelPort,
    /// Enumeration matching device class 07h, subclass 01h, interface function 03h.
    CommunicationController_Parallel_Ieee1284Controller,
    /// Enumeration matching device class 07h, subclass 01h, interface function FEh.
    CommunicationController_Parallel_Ieee1284TargetDevice,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 01h.
    CommunicationController_Parallel_Unknown(u8),
    /// Enumeration matching device class 07h, subclass 02h, interface function 00h.
    CommunicationController_MultiportSerialController_Default,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 02h.
    CommunicationController_MultiportSerialController_Unknown(u8),
    /// Enumeration matching device class 07h, subclass 03h, interface function 00h.
    CommunicationController_Modem_Generic,
    /// Enumeration matching device class 07h, subclass 03h, interface function 01h.
    CommunicationController_Modem_Hayes16450Compatible,
    /// Enumeration matching device class 07h, subclass 03h, interface function 02h.
    CommunicationController_Modem_Hayes16550Compatible,
    /// Enumeration matching device class 07h, subclass 03h, interface function 03h.
    CommunicationController_Modem_Hayes16650Compatible,
    /// Enumeration matching device class 07h, subclass 03h, interface function 04h.
    CommunicationController_Modem_Hayes16750Compatible,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 03h.
    CommunicationController_Modem_Unknown(u8),
    /// Enumeration matching device class 07h, subclass 04h, interface function 00h.
    CommunicationController_GpibController_Default,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 04h.
    CommunicationController_GpibController_Unknown(u8),
    /// Enumeration matching device class 07h, subclass 05h, interface function 00h.
    CommunicationController_Smartcard_Default,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 05h.
    CommunicationController_Smartcard_Unknown(u8),
    /// Enumeration matching device class 07h, subclass 80h, interface function 00h.
    CommunicationController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 07h, subclass 80h.
    CommunicationController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 07h.
    CommunicationController_Unknown(u8, u8),
    /// Enumeration matching device class 08h, subclass 00h, interface function 00h.
    BaseSystemPeripheral_PIC_Generic8259,
    /// Enumeration matching device class 08h, subclass 00h, interface function 01h.
    BaseSystemPeripheral_PIC_Isa,
    /// Enumeration matching device class 08h, subclass 00h, interface function 02h.
    BaseSystemPeripheral_PIC_Eisa,
    /// Enumeration matching device class 08h, subclass 00h, interface function 10h.
    BaseSystemPeripheral_PIC_IoApic,
    /// Enumeration matching device class 08h, subclass 00h, interface function 20h.
    BaseSystemPeripheral_PIC_IoXApic,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 00h.
    BaseSystemPeripheral_PIC_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 01h, interface function 00h.
    BaseSystemPeripheral_DmaController_Generic8237,
    /// Enumeration matching device class 08h, subclass 01h, interface function 01h.
    BaseSystemPeripheral_DmaController_Isa,
    /// Enumeration matching device class 08h, subclass 01h, interface function 02h.
    BaseSystemPeripheral_DmaController_Eisa,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 01h.
    BaseSystemPeripheral_DmaController_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 02h, interface function 00h.
    BaseSystemPeripheral_SystemTimer_Generic8254,
    /// Enumeration matching device class 08h, subclass 02h, interface function 01h.
    BaseSystemPeripheral_SystemTimer_Isa,
    /// Enumeration matching device class 08h, subclass 02h, interface function 02h.
    BaseSystemPeripheral_SystemTimer_Eisa,
    /// Enumeration matching device class 08h, subclass 02h, interface function 03h.
    BaseSystemPeripheral_SystemTimer_HighPerformanceEventTimer,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 02h.
    BaseSystemPeripheral_SystemTimer_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 03h, interface function 00h.
    BaseSystemPeripheral_RealTimeClockController_GenericRtc,
    /// Enumeration matching device class 08h, subclass 03h, interface function 01h.
    BaseSystemPeripheral_RealTimeClockController_Isa,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 03h.
    BaseSystemPeripheral_RealTimeClockController_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 04h, interface function 00h.
    BaseSystemPeripheral_GenericPciHotPlugController_Default,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 04h.
    BaseSystemPeripheral_GenericPciHotPlugController_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 05h, interface function 00h.
    BaseSystemPeripheral_SdHostController_Default,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 05h.
    BaseSystemPeripheral_SdHostController_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 06h, interface function 00h.
    BaseSystemPeripheral_IOMMU_Default,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 06h.
    BaseSystemPeripheral_IOMMU_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 07h, interface function 00h.
    BaseSystemPeripheral_RootComplexEventCollector_Default,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 07h.
    BaseSystemPeripheral_RootComplexEventCollector_Unknown(u8),
    /// Enumeration matching device class 08h, subclass 80h, interface function 00h.
    BaseSystemPeripheral_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 08h, subclass 80h.
    BaseSystemPeripheral_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 08h.
    BaseSystemPeripheral_Unknown(u8, u8),
    /// Enumeration matching device class 09h, subclass 00h, interface function 00h.
    InputDevice_KeyboardController_Default,
    /// Enumeration matching unknown interface function values of device class 09h, subclass 00h.
    InputDevice_KeyboardController_Unknown(u8),
    /// Enumeration matching device class 09h, subclass 01h, interface function 00h.
    InputDevice_DigitizerPenController_Default,
    /// Enumeration matching unknown interface function values of device class 09h, subclass 01h.
    InputDevice_DigitizerPenController_Unknown(u8),
    /// Enumeration matching device class 09h, subclass 02h, interface function 00h.
    InputDevice_MouseController_Default,
    /// Enumeration matching unknown interface function values of device class 09h, subclass 02h.
    InputDevice_MouseController_Unknown(u8),
    /// Enumeration matching device class 09h, subclass 03h, interface function 00h.
    InputDevice_ScannerController_Default,
    /// Enumeration matching unknown interface function values of device class 09h, subclass 03h.
    InputDevice_ScannerController_Unknown(u8),
    /// Enumeration matching device class 09h, subclass 04h, interface function 00h.
    InputDevice_GameportController_Generic,
    /// Enumeration matching device class 09h, subclass 04h, interface function 10h.
    InputDevice_GameportController_LegacyGamePort,
    /// Enumeration matching unknown interface function values of device class 09h, subclass 04h.
    InputDevice_GameportController_Unknown(u8),
    /// Enumeration matching device class 09h, subclass 80h, interface function 00h.
    InputDevice_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 09h, subclass 80h.
    InputDevice_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 09h.
    InputDevice_Unknown(u8, u8),
    /// Enumeration matching device class 0Ah, subclass 00h, interface function 00h.
    DockingStation_Generic_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Ah, subclass 00h.
    DockingStation_Generic_Unknown(u8),
    /// Enumeration matching device class 0Ah, subclass 80h, interface function 00h.
    DockingStation_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Ah, subclass 80h.
    DockingStation_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 0Ah.
    DockingStation_Unknown(u8, u8),
    /// Enumeration matching device class 0Bh, subclass 00h, interface function 00h.
    Processor_Intel386_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 00h.
    Processor_Intel386_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 01h, interface function 00h.
    Processor_Intel486_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 01h.
    Processor_Intel486_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 02h, interface function 00h.
    Processor_IntelPentium_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 02h.
    Processor_IntelPentium_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 10h, interface function 00h.
    Processor_DecAlpha_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 10h.
    Processor_DecAlpha_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 20h, interface function 00h.
    Processor_PowerPc_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 20h.
    Processor_PowerPc_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 30h, interface function 00h.
    Processor_Mips_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 30h.
    Processor_Mips_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 40h, interface function 00h.
    Processor_Coprocessor_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 40h.
    Processor_Coprocessor_Unknown(u8),
    /// Enumeration matching device class 0Bh, subclass 80h, interface function 00h.
    Processor_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Bh, subclass 80h.
    Processor_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 0Bh.
    Processor_Unknown(u8, u8),
    /// Enumeration matching device class 0Ch, subclass 00h, interface function 00h.
    SerialBusController_Ieee1394_FireWire,
    /// Enumeration matching device class 0Ch, subclass 00h, interface function 10h.
    SerialBusController_Ieee1394_Ieee1394OpenHCI,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 00h.
    SerialBusController_Ieee1394_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 01h, interface function 00h.
    SerialBusController_ACCESSbus_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 01h.
    SerialBusController_ACCESSbus_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 02h, interface function 00h.
    SerialBusController_SSA_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 02h.
    SerialBusController_SSA_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 03h, interface function 00h.
    SerialBusController_USB_UhcsController,
    /// Enumeration matching device class 0Ch, subclass 03h, interface function 10h.
    SerialBusController_USB_OhcsController,
    /// Enumeration matching device class 0Ch, subclass 03h, interface function 20h.
    SerialBusController_USB_Usb2Ehci,
    /// Enumeration matching device class 0Ch, subclass 03h, interface function 30h.
    SerialBusController_USB_Usb3Xhci,
    /// Enumeration matching device class 0Ch, subclass 03h, interface function 40h.
    SerialBusController_USB_Usb4HostInterface,
    /// Enumeration matching device class 0Ch, subclass 03h, interface function 80h.
    SerialBusController_USB_UsbGeneric,
    /// Enumeration matching device class 0Ch, subclass 03h, interface function FEh.
    SerialBusController_USB_UsbDevice,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 03h.
    SerialBusController_USB_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 04h, interface function 00h.
    SerialBusController_FibreChannel_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 04h.
    SerialBusController_FibreChannel_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 05h, interface function 00h.
    SerialBusController_SystemManagementBus_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 05h.
    SerialBusController_SystemManagementBus_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 06h, interface function 00h.
    SerialBusController_InfiniBandDeprecated_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 06h.
    SerialBusController_InfiniBandDeprecated_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 07h, interface function 00h.
    SerialBusController_Ipmi_Smic,
    /// Enumeration matching device class 0Ch, subclass 07h, interface function 01h.
    SerialBusController_Ipmi_KeyboardControllerStyle,
    /// Enumeration matching device class 0Ch, subclass 07h, interface function 02h.
    SerialBusController_Ipmi_BlockTransferInterface,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 07h.
    SerialBusController_Ipmi_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 08h, interface function 00h.
    SerialBusController_SERCOS_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 08h.
    SerialBusController_SERCOS_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 09h, interface function 00h.
    SerialBusController_CANbus_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 09h.
    SerialBusController_CANbus_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 0Ah, interface function 00h.
    SerialBusController_MipiI3C_Default,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 0Ah.
    SerialBusController_MipiI3C_Unknown(u8),
    /// Enumeration matching device class 0Ch, subclass 80h, interface function 00h.
    SerialBusController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Ch, subclass 80h.
    SerialBusController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 0Ch.
    SerialBusController_Unknown(u8, u8),
    /// Enumeration matching device class 0Dh, subclass 00h, interface function 00h.
    WirelessController_iRDA_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 00h.
    WirelessController_iRDA_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 01h, interface function 00h.
    WirelessController_Radio_ConsumerIR,
    /// Enumeration matching device class 0Dh, subclass 01h, interface function 10h.
    WirelessController_Radio_UWB,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 01h.
    WirelessController_Radio_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 10h, interface function 00h.
    WirelessController_RFController_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 10h.
    WirelessController_RFController_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 11h, interface function 00h.
    WirelessController_Bluetooth_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 11h.
    WirelessController_Bluetooth_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 12h, interface function 00h.
    WirelessController_Broadband_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 12h.
    WirelessController_Broadband_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 20h, interface function 00h.
    WirelessController_Wifi802_11A_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 20h.
    WirelessController_Wifi802_11A_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 21h, interface function 00h.
    WirelessController_Wifi802_11B_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 21h.
    WirelessController_Wifi802_11B_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 40h, interface function 00h.
    WirelessController_CellularController_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 40h.
    WirelessController_CellularController_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 41h, interface function 00h.
    WirelessController_CellularControllerWithEthernet_Default,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 41h.
    WirelessController_CellularControllerWithEthernet_Unknown(u8),
    /// Enumeration matching device class 0Dh, subclass 80h, interface function 00h.
    WirelessController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Dh, subclass 80h.
    WirelessController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 0Dh.
    WirelessController_Unknown(u8, u8),
    /// Enumeration matching device class 0Eh, subclass 00h, interface function 00h.
    IntelligentIoController_IntelligentIoController_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Eh, subclass 00h.
    IntelligentIoController_IntelligentIoController_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 0Eh.
    IntelligentIoController_Unknown(u8, u8),
    /// Enumeration matching device class 0Fh, subclass 01h, interface function 00h.
    SatelliteCommController_Tv_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Fh, subclass 01h.
    SatelliteCommController_Tv_Unknown(u8),
    /// Enumeration matching device class 0Fh, subclass 02h, interface function 00h.
    SatelliteCommController_Audio_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Fh, subclass 02h.
    SatelliteCommController_Audio_Unknown(u8),
    /// Enumeration matching device class 0Fh, subclass 03h, interface function 00h.
    SatelliteCommController_Voice_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Fh, subclass 03h.
    SatelliteCommController_Voice_Unknown(u8),
    /// Enumeration matching device class 0Fh, subclass 04h, interface function 00h.
    SatelliteCommController_Data_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Fh, subclass 04h.
    SatelliteCommController_Data_Unknown(u8),
    /// Enumeration matching device class 0Fh, subclass 80h, interface function 00h.
    SatelliteCommController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 0Fh, subclass 80h.
    SatelliteCommController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 0Fh.
    SatelliteCommController_Unknown(u8, u8),
    /// Enumeration matching device class 10h, subclass 00h, interface function 00h.
    EncryptionController_NetworkandComputingEncrpytionDecryption_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 10h, subclass 00h.
    EncryptionController_NetworkandComputingEncrpytionDecryption_Unknown(u8),
    /// Enumeration matching device class 10h, subclass 10h, interface function 00h.
    EncryptionController_EntertainmentEncryptionDecryption_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 10h, subclass 10h.
    EncryptionController_EntertainmentEncryptionDecryption_Unknown(u8),
    /// Enumeration matching device class 10h, subclass 80h, interface function 00h.
    EncryptionController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 10h, subclass 80h.
    EncryptionController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 10h.
    EncryptionController_Unknown(u8, u8),
    /// Enumeration matching device class 11h, subclass 00h, interface function 00h.
    SignalProcessingController_DpIoModule_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 11h, subclass 00h.
    SignalProcessingController_DpIoModule_Unknown(u8),
    /// Enumeration matching device class 11h, subclass 01h, interface function 00h.
    SignalProcessingController_PerformanceCounters_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 11h, subclass 01h.
    SignalProcessingController_PerformanceCounters_Unknown(u8),
    /// Enumeration matching device class 11h, subclass 10h, interface function 00h.
    SignalProcessingController_CommunicationSynchronization_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 11h, subclass 10h.
    SignalProcessingController_CommunicationSynchronization_Unknown(u8),
    /// Enumeration matching device class 11h, subclass 20h, interface function 00h.
    SignalProcessingController_ManagementCard_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 11h, subclass 20h.
    SignalProcessingController_ManagementCard_Unknown(u8),
    /// Enumeration matching device class 11h, subclass 80h, interface function 00h.
    SignalProcessingController_Other_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 11h, subclass 80h.
    SignalProcessingController_Other_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 11h.
    SignalProcessingController_Unknown(u8, u8),
    /// Enumeration matching device class 12h, subclass 00h, interface function 00h.
    ProcessingAccelerator_VendorSpecific_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 12h, subclass 00h.
    ProcessingAccelerator_VendorSpecific_Unknown(u8),
    /// Enumeration matching device class 12h, subclass 01h, interface function 00h.
    ProcessingAccelerator_SniaSdxiController_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 12h, subclass 01h.
    ProcessingAccelerator_SniaSdxiController_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 12h.
    ProcessingAccelerator_Unknown(u8, u8),
    /// Enumeration matching device class 13h, subclass 00h, interface function 00h.
    NonEssentialInstrumentation_VendorSpecific_VendorSpecific,
    /// Enumeration matching unknown interface function values of device class 13h, subclass 00h.
    NonEssentialInstrumentation_VendorSpecific_Unknown(u8),
    /// Enumeration matching unknown subclass values of device class 13h.
    NonEssentialInstrumentation_Unknown(u8, u8),
    /// Enumeration matching unknown combinations of device class / subclass / interface function.
    Unknown(u8, u8, u8),
}

impl PciDeviceInterfaceFunc {
    /// Converts a combination of `class_code`, `subclass_code` and
    /// `interface_func` to a valid `PciDeviceInterfaceFunc` object.
    pub fn from_codes(class_code: u8, subclass_code: u8, interface_func: u8) -> Self {
        match (class_code, subclass_code, interface_func) {
            (0x00, 0x00, 0x00) => Self::Unclassified_Generic_VendorSpecific,
            (0x00, 0x00, unk_i) => Self::Unclassified_Generic_Unknown(unk_i),
            (0x00, 0x01, 0x00) => Self::Unclassified_VgaCompatible_VendorSpecific,
            (0x00, 0x01, unk_i) => Self::Unclassified_VgaCompatible_Unknown(unk_i),
            (0x00, unk_s, unk_i) => Self::Unclassified_Unknown(unk_s, unk_i),
            (0x01, 0x00, 0x00) => Self::MassStorageController_Scsi_VendorSpecific,
            (0x01, 0x00, 0x11) => Self::MassStorageController_Scsi_StorageDevice,
            (0x01, 0x00, 0x12) => Self::MassStorageController_Scsi_HostBusAdapter,
            (0x01, 0x00, 0x13) => Self::MassStorageController_Scsi_StorageDeviceAndController,
            (0x01, 0x00, 0x21) => Self::MassStorageController_Scsi_StorageDeviceOverPciE,
            (0x01, 0x00, unk_i) => Self::MassStorageController_Scsi_Unknown(unk_i),
            (0x01, 0x01, if_code) => Self::MassStorageController_Ide_AtaInterface(if_code),
            (0x01, 0x02, 0x00) => Self::MassStorageController_FloppyDisk_VendorSpecific,
            (0x01, 0x02, unk_i) => Self::MassStorageController_FloppyDisk_Unknown(unk_i),
            (0x01, 0x03, 0x00) => Self::MassStorageController_IpiBus_VendorSpecific,
            (0x01, 0x03, unk_i) => Self::MassStorageController_IpiBus_Unknown(unk_i),
            (0x01, 0x04, 0x00) => Self::MassStorageController_Raid_VendorSpecific,
            (0x01, 0x04, unk_i) => Self::MassStorageController_Raid_Unknown(unk_i),
            (0x01, 0x05, 0x20) => Self::MassStorageController_AtaWithAdma_SingleStepping,
            (0x01, 0x05, 0x30) => Self::MassStorageController_AtaWithAdma_ContinuousOperation,
            (0x01, 0x05, unk_i) => Self::MassStorageController_AtaWithAdma_Unknown(unk_i),
            (0x01, 0x06, 0x00) => Self::MassStorageController_SerialAta_VendorSpecific,
            (0x01, 0x06, 0x01) => Self::MassStorageController_SerialAta_Ahci,
            (0x01, 0x06, 0x02) => Self::MassStorageController_SerialAta_SerialStorageBus,
            (0x01, 0x06, unk_i) => Self::MassStorageController_SerialAta_Unknown(unk_i),
            (0x01, 0x07, 0x00) => Self::MassStorageController_SerialAttachedScsi_VendorSpecific,
            (0x01, 0x07, 0x01) => Self::MassStorageController_SerialAttachedScsi_Obsolete,
            (0x01, 0x07, unk_i) => Self::MassStorageController_SerialAttachedScsi_Unknown(unk_i),
            (0x01, 0x08, 0x00) => Self::MassStorageController_NonVolatileMemory_VendorSpecific,
            (0x01, 0x08, 0x01) => Self::MassStorageController_NonVolatileMemory_NvmHci,
            (0x01, 0x08, 0x02) => Self::MassStorageController_NonVolatileMemory_NVMeIoController,
            (0x01, 0x08, 0x03) => Self::MassStorageController_NonVolatileMemory_NVMeAdministrativeController,
            (0x01, 0x08, unk_i) => Self::MassStorageController_NonVolatileMemory_Unknown(unk_i),
            (0x01, 0x09, 0x00) => Self::MassStorageController_UniversalFlashStorage_VendorSpecific,
            (0x01, 0x09, 0x01) => Self::MassStorageController_UniversalFlashStorage_UfsHci,
            (0x01, 0x09, unk_i) => Self::MassStorageController_UniversalFlashStorage_Unknown(unk_i),
            (0x01, 0x80, 0x00) => Self::MassStorageController_Other_VendorSpecific,
            (0x01, 0x80, unk_i) => Self::MassStorageController_Other_Unknown(unk_i),
            (0x01, unk_s, unk_i) => Self::MassStorageController_Unknown(unk_s, unk_i),
            (0x02, 0x00, 0x00) => Self::NetworkController_Ethernet_Default,
            (0x02, 0x00, unk_i) => Self::NetworkController_Ethernet_Unknown(unk_i),
            (0x02, 0x01, 0x00) => Self::NetworkController_TokenRing_Default,
            (0x02, 0x01, unk_i) => Self::NetworkController_TokenRing_Unknown(unk_i),
            (0x02, 0x02, 0x00) => Self::NetworkController_Fddi_Default,
            (0x02, 0x02, unk_i) => Self::NetworkController_Fddi_Unknown(unk_i),
            (0x02, 0x03, 0x00) => Self::NetworkController_Atm_Default,
            (0x02, 0x03, unk_i) => Self::NetworkController_Atm_Unknown(unk_i),
            (0x02, 0x04, 0x00) => Self::NetworkController_Isdn_Default,
            (0x02, 0x04, unk_i) => Self::NetworkController_Isdn_Unknown(unk_i),
            (0x02, 0x05, 0x00) => Self::NetworkController_WorldFip_Default,
            (0x02, 0x05, unk_i) => Self::NetworkController_WorldFip_Unknown(unk_i),
            (0x02, 0x06, if_code) => Self::NetworkController_PicMg214MultiComputing_PicMg(if_code),
            (0x02, 0x07, 0x00) => Self::NetworkController_InfiniBand_Default,
            (0x02, 0x07, unk_i) => Self::NetworkController_InfiniBand_Unknown(unk_i),
            (0x02, 0x80, 0x00) => Self::NetworkController_Other_VendorSpecific,
            (0x02, 0x80, unk_i) => Self::NetworkController_Other_Unknown(unk_i),
            (0x02, unk_s, unk_i) => Self::NetworkController_Unknown(unk_s, unk_i),
            (0x03, 0x00, 0x00) => Self::DisplayController_VgaCompatible_Vga,
            (0x03, 0x00, 0x01) => Self::DisplayController_VgaCompatible_Ibm8514,
            (0x03, 0x00, unk_i) => Self::DisplayController_VgaCompatible_Unknown(unk_i),
            (0x03, 0x01, 0x00) => Self::DisplayController_Xga_Default,
            (0x03, 0x01, unk_i) => Self::DisplayController_Xga_Unknown(unk_i),
            (0x03, 0x02, 0x00) => Self::DisplayController_NonVga3D_VendorSpecific,
            (0x03, 0x02, unk_i) => Self::DisplayController_NonVga3D_Unknown(unk_i),
            (0x03, 0x80, 0x00) => Self::DisplayController_Other_VendorSpecific,
            (0x03, 0x80, unk_i) => Self::DisplayController_Other_Unknown(unk_i),
            (0x03, unk_s, unk_i) => Self::DisplayController_Unknown(unk_s, unk_i),
            (0x04, 0x00, 0x00) => Self::MultimediaDevice_VideoDevice_VendorSpecific,
            (0x04, 0x00, unk_i) => Self::MultimediaDevice_VideoDevice_Unknown(unk_i),
            (0x04, 0x01, 0x00) => Self::MultimediaDevice_AudioDevice_VendorSpecific,
            (0x04, 0x01, unk_i) => Self::MultimediaDevice_AudioDevice_Unknown(unk_i),
            (0x04, 0x02, 0x00) => Self::MultimediaDevice_ComputerTelephony_VendorSpecific,
            (0x04, 0x02, unk_i) => Self::MultimediaDevice_ComputerTelephony_Unknown(unk_i),
            (0x04, 0x03, 0x00) => Self::MultimediaDevice_HdaCompatible_HighDefinitionAudio,
            (0x04, 0x03, 0x80) => Self::MultimediaDevice_HdaCompatible_HighDefinitionAudioWithVendorExtension,
            (0x04, 0x03, unk_i) => Self::MultimediaDevice_HdaCompatible_Unknown(unk_i),
            (0x04, 0x80, 0x00) => Self::MultimediaDevice_Other_VendorSpecific,
            (0x04, 0x80, unk_i) => Self::MultimediaDevice_Other_Unknown(unk_i),
            (0x04, unk_s, unk_i) => Self::MultimediaDevice_Unknown(unk_s, unk_i),
            (0x05, 0x00, 0x00) => Self::MemoryController_Ram_Default,
            (0x05, 0x00, unk_i) => Self::MemoryController_Ram_Unknown(unk_i),
            (0x05, 0x01, 0x00) => Self::MemoryController_Flash_Default,
            (0x05, 0x01, unk_i) => Self::MemoryController_Flash_Unknown(unk_i),
            (0x05, 0x02, 0x00) => Self::MemoryController_CxlMemory_VendorSpecific,
            (0x05, 0x02, 0x10) => Self::MemoryController_CxlMemory_Cxl2Specifications,
            (0x05, 0x02, unk_i) => Self::MemoryController_CxlMemory_Unknown(unk_i),
            (0x05, 0x80, 0x00) => Self::MemoryController_Other_VendorSpecific,
            (0x05, 0x80, unk_i) => Self::MemoryController_Other_Unknown(unk_i),
            (0x05, unk_s, unk_i) => Self::MemoryController_Unknown(unk_s, unk_i),
            (0x06, 0x00, 0x00) => Self::Bridge_HostBridge_Default,
            (0x06, 0x00, unk_i) => Self::Bridge_HostBridge_Unknown(unk_i),
            (0x06, 0x01, 0x00) => Self::Bridge_IsaBridge_Default,
            (0x06, 0x01, unk_i) => Self::Bridge_IsaBridge_Unknown(unk_i),
            (0x06, 0x02, 0x00) => Self::Bridge_EisaBridge_Default,
            (0x06, 0x02, unk_i) => Self::Bridge_EisaBridge_Unknown(unk_i),
            (0x06, 0x03, 0x00) => Self::Bridge_McaBridge_Default,
            (0x06, 0x03, unk_i) => Self::Bridge_McaBridge_Unknown(unk_i),
            (0x06, 0x04, 0x00) => Self::Bridge_PciToPciBridge_PciToPci,
            (0x06, 0x04, 0x01) => Self::Bridge_PciToPciBridge_SubtractiveDecodePciToPci,
            (0x06, 0x04, unk_i) => Self::Bridge_PciToPciBridge_Unknown(unk_i),
            (0x06, 0x05, 0x00) => Self::Bridge_PcmciaBridge_Default,
            (0x06, 0x05, unk_i) => Self::Bridge_PcmciaBridge_Unknown(unk_i),
            (0x06, 0x06, 0x00) => Self::Bridge_NuBusBridge_Default,
            (0x06, 0x06, unk_i) => Self::Bridge_NuBusBridge_Unknown(unk_i),
            (0x06, 0x07, 0x00) => Self::Bridge_CardBusBridge_Default,
            (0x06, 0x07, unk_i) => Self::Bridge_CardBusBridge_Unknown(unk_i),
            (0x06, 0x08, 0x00) => Self::Bridge_RacewayBridge_Default,
            (0x06, 0x08, unk_i) => Self::Bridge_RacewayBridge_Unknown(unk_i),
            (0x06, 0x09, 0x40) => Self::Bridge_SemiTransparentPciToPciBridge_Primary,
            (0x06, 0x09, 0x80) => Self::Bridge_SemiTransparentPciToPciBridge_Secondary,
            (0x06, 0x09, unk_i) => Self::Bridge_SemiTransparentPciToPciBridge_Unknown(unk_i),
            (0x06, 0x0a, 0x00) => Self::Bridge_InfiniBandtoPciHostBridge_Default,
            (0x06, 0x0a, unk_i) => Self::Bridge_InfiniBandtoPciHostBridge_Unknown(unk_i),
            (0x06, 0x0b, 0x00) => Self::Bridge_AdvancedSwitchingToPciHostBridge_VendorSpecific,
            (0x06, 0x0b, 0x01) => Self::Bridge_AdvancedSwitchingToPciHostBridge_AsiSigInterface,
            (0x06, 0x0b, unk_i) => Self::Bridge_AdvancedSwitchingToPciHostBridge_Unknown(unk_i),
            (0x06, 0x80, 0x00) => Self::Bridge_Other_VendorSpecific,
            (0x06, 0x80, unk_i) => Self::Bridge_Other_Unknown(unk_i),
            (0x06, unk_s, unk_i) => Self::Bridge_Unknown(unk_s, unk_i),
            (0x07, 0x00, 0x00) => Self::CommunicationController_Serial_Uart8250,
            (0x07, 0x00, 0x01) => Self::CommunicationController_Serial_Uart16450,
            (0x07, 0x00, 0x02) => Self::CommunicationController_Serial_Uart16550,
            (0x07, 0x00, 0x03) => Self::CommunicationController_Serial_Uart16650,
            (0x07, 0x00, 0x04) => Self::CommunicationController_Serial_Uart16750,
            (0x07, 0x00, 0x05) => Self::CommunicationController_Serial_Uart16850,
            (0x07, 0x00, 0x06) => Self::CommunicationController_Serial_Uart16950,
            (0x07, 0x00, unk_i) => Self::CommunicationController_Serial_Unknown(unk_i),
            (0x07, 0x01, 0x00) => Self::CommunicationController_Parallel_ParallelPort,
            (0x07, 0x01, 0x01) => Self::CommunicationController_Parallel_BidirectionalParallelPort,
            (0x07, 0x01, 0x02) => Self::CommunicationController_Parallel_EcpParallelPort,
            (0x07, 0x01, 0x03) => Self::CommunicationController_Parallel_Ieee1284Controller,
            (0x07, 0x01, 0xfe) => Self::CommunicationController_Parallel_Ieee1284TargetDevice,
            (0x07, 0x01, unk_i) => Self::CommunicationController_Parallel_Unknown(unk_i),
            (0x07, 0x02, 0x00) => Self::CommunicationController_MultiportSerialController_Default,
            (0x07, 0x02, unk_i) => Self::CommunicationController_MultiportSerialController_Unknown(unk_i),
            (0x07, 0x03, 0x00) => Self::CommunicationController_Modem_Generic,
            (0x07, 0x03, 0x01) => Self::CommunicationController_Modem_Hayes16450Compatible,
            (0x07, 0x03, 0x02) => Self::CommunicationController_Modem_Hayes16550Compatible,
            (0x07, 0x03, 0x03) => Self::CommunicationController_Modem_Hayes16650Compatible,
            (0x07, 0x03, 0x04) => Self::CommunicationController_Modem_Hayes16750Compatible,
            (0x07, 0x03, unk_i) => Self::CommunicationController_Modem_Unknown(unk_i),
            (0x07, 0x04, 0x00) => Self::CommunicationController_GpibController_Default,
            (0x07, 0x04, unk_i) => Self::CommunicationController_GpibController_Unknown(unk_i),
            (0x07, 0x05, 0x00) => Self::CommunicationController_Smartcard_Default,
            (0x07, 0x05, unk_i) => Self::CommunicationController_Smartcard_Unknown(unk_i),
            (0x07, 0x80, 0x00) => Self::CommunicationController_Other_VendorSpecific,
            (0x07, 0x80, unk_i) => Self::CommunicationController_Other_Unknown(unk_i),
            (0x07, unk_s, unk_i) => Self::CommunicationController_Unknown(unk_s, unk_i),
            (0x08, 0x00, 0x00) => Self::BaseSystemPeripheral_PIC_Generic8259,
            (0x08, 0x00, 0x01) => Self::BaseSystemPeripheral_PIC_Isa,
            (0x08, 0x00, 0x02) => Self::BaseSystemPeripheral_PIC_Eisa,
            (0x08, 0x00, 0x10) => Self::BaseSystemPeripheral_PIC_IoApic,
            (0x08, 0x00, 0x20) => Self::BaseSystemPeripheral_PIC_IoXApic,
            (0x08, 0x00, unk_i) => Self::BaseSystemPeripheral_PIC_Unknown(unk_i),
            (0x08, 0x01, 0x00) => Self::BaseSystemPeripheral_DmaController_Generic8237,
            (0x08, 0x01, 0x01) => Self::BaseSystemPeripheral_DmaController_Isa,
            (0x08, 0x01, 0x02) => Self::BaseSystemPeripheral_DmaController_Eisa,
            (0x08, 0x01, unk_i) => Self::BaseSystemPeripheral_DmaController_Unknown(unk_i),
            (0x08, 0x02, 0x00) => Self::BaseSystemPeripheral_SystemTimer_Generic8254,
            (0x08, 0x02, 0x01) => Self::BaseSystemPeripheral_SystemTimer_Isa,
            (0x08, 0x02, 0x02) => Self::BaseSystemPeripheral_SystemTimer_Eisa,
            (0x08, 0x02, 0x03) => Self::BaseSystemPeripheral_SystemTimer_HighPerformanceEventTimer,
            (0x08, 0x02, unk_i) => Self::BaseSystemPeripheral_SystemTimer_Unknown(unk_i),
            (0x08, 0x03, 0x00) => Self::BaseSystemPeripheral_RealTimeClockController_GenericRtc,
            (0x08, 0x03, 0x01) => Self::BaseSystemPeripheral_RealTimeClockController_Isa,
            (0x08, 0x03, unk_i) => Self::BaseSystemPeripheral_RealTimeClockController_Unknown(unk_i),
            (0x08, 0x04, 0x00) => Self::BaseSystemPeripheral_GenericPciHotPlugController_Default,
            (0x08, 0x04, unk_i) => Self::BaseSystemPeripheral_GenericPciHotPlugController_Unknown(unk_i),
            (0x08, 0x05, 0x00) => Self::BaseSystemPeripheral_SdHostController_Default,
            (0x08, 0x05, unk_i) => Self::BaseSystemPeripheral_SdHostController_Unknown(unk_i),
            (0x08, 0x06, 0x00) => Self::BaseSystemPeripheral_IOMMU_Default,
            (0x08, 0x06, unk_i) => Self::BaseSystemPeripheral_IOMMU_Unknown(unk_i),
            (0x08, 0x07, 0x00) => Self::BaseSystemPeripheral_RootComplexEventCollector_Default,
            (0x08, 0x07, unk_i) => Self::BaseSystemPeripheral_RootComplexEventCollector_Unknown(unk_i),
            (0x08, 0x80, 0x00) => Self::BaseSystemPeripheral_Other_VendorSpecific,
            (0x08, 0x80, unk_i) => Self::BaseSystemPeripheral_Other_Unknown(unk_i),
            (0x08, unk_s, unk_i) => Self::BaseSystemPeripheral_Unknown(unk_s, unk_i),
            (0x09, 0x00, 0x00) => Self::InputDevice_KeyboardController_Default,
            (0x09, 0x00, unk_i) => Self::InputDevice_KeyboardController_Unknown(unk_i),
            (0x09, 0x01, 0x00) => Self::InputDevice_DigitizerPenController_Default,
            (0x09, 0x01, unk_i) => Self::InputDevice_DigitizerPenController_Unknown(unk_i),
            (0x09, 0x02, 0x00) => Self::InputDevice_MouseController_Default,
            (0x09, 0x02, unk_i) => Self::InputDevice_MouseController_Unknown(unk_i),
            (0x09, 0x03, 0x00) => Self::InputDevice_ScannerController_Default,
            (0x09, 0x03, unk_i) => Self::InputDevice_ScannerController_Unknown(unk_i),
            (0x09, 0x04, 0x00) => Self::InputDevice_GameportController_Generic,
            (0x09, 0x04, 0x10) => Self::InputDevice_GameportController_LegacyGamePort,
            (0x09, 0x04, unk_i) => Self::InputDevice_GameportController_Unknown(unk_i),
            (0x09, 0x80, 0x00) => Self::InputDevice_Other_VendorSpecific,
            (0x09, 0x80, unk_i) => Self::InputDevice_Other_Unknown(unk_i),
            (0x09, unk_s, unk_i) => Self::InputDevice_Unknown(unk_s, unk_i),
            (0x0a, 0x00, 0x00) => Self::DockingStation_Generic_VendorSpecific,
            (0x0a, 0x00, unk_i) => Self::DockingStation_Generic_Unknown(unk_i),
            (0x0a, 0x80, 0x00) => Self::DockingStation_Other_VendorSpecific,
            (0x0a, 0x80, unk_i) => Self::DockingStation_Other_Unknown(unk_i),
            (0x0a, unk_s, unk_i) => Self::DockingStation_Unknown(unk_s, unk_i),
            (0x0b, 0x00, 0x00) => Self::Processor_Intel386_VendorSpecific,
            (0x0b, 0x00, unk_i) => Self::Processor_Intel386_Unknown(unk_i),
            (0x0b, 0x01, 0x00) => Self::Processor_Intel486_VendorSpecific,
            (0x0b, 0x01, unk_i) => Self::Processor_Intel486_Unknown(unk_i),
            (0x0b, 0x02, 0x00) => Self::Processor_IntelPentium_VendorSpecific,
            (0x0b, 0x02, unk_i) => Self::Processor_IntelPentium_Unknown(unk_i),
            (0x0b, 0x10, 0x00) => Self::Processor_DecAlpha_VendorSpecific,
            (0x0b, 0x10, unk_i) => Self::Processor_DecAlpha_Unknown(unk_i),
            (0x0b, 0x20, 0x00) => Self::Processor_PowerPc_VendorSpecific,
            (0x0b, 0x20, unk_i) => Self::Processor_PowerPc_Unknown(unk_i),
            (0x0b, 0x30, 0x00) => Self::Processor_Mips_VendorSpecific,
            (0x0b, 0x30, unk_i) => Self::Processor_Mips_Unknown(unk_i),
            (0x0b, 0x40, 0x00) => Self::Processor_Coprocessor_VendorSpecific,
            (0x0b, 0x40, unk_i) => Self::Processor_Coprocessor_Unknown(unk_i),
            (0x0b, 0x80, 0x00) => Self::Processor_Other_VendorSpecific,
            (0x0b, 0x80, unk_i) => Self::Processor_Other_Unknown(unk_i),
            (0x0b, unk_s, unk_i) => Self::Processor_Unknown(unk_s, unk_i),
            (0x0c, 0x00, 0x00) => Self::SerialBusController_Ieee1394_FireWire,
            (0x0c, 0x00, 0x10) => Self::SerialBusController_Ieee1394_Ieee1394OpenHCI,
            (0x0c, 0x00, unk_i) => Self::SerialBusController_Ieee1394_Unknown(unk_i),
            (0x0c, 0x01, 0x00) => Self::SerialBusController_ACCESSbus_Default,
            (0x0c, 0x01, unk_i) => Self::SerialBusController_ACCESSbus_Unknown(unk_i),
            (0x0c, 0x02, 0x00) => Self::SerialBusController_SSA_Default,
            (0x0c, 0x02, unk_i) => Self::SerialBusController_SSA_Unknown(unk_i),
            (0x0c, 0x03, 0x00) => Self::SerialBusController_USB_UhcsController,
            (0x0c, 0x03, 0x10) => Self::SerialBusController_USB_OhcsController,
            (0x0c, 0x03, 0x20) => Self::SerialBusController_USB_Usb2Ehci,
            (0x0c, 0x03, 0x30) => Self::SerialBusController_USB_Usb3Xhci,
            (0x0c, 0x03, 0x40) => Self::SerialBusController_USB_Usb4HostInterface,
            (0x0c, 0x03, 0x80) => Self::SerialBusController_USB_UsbGeneric,
            (0x0c, 0x03, 0xfe) => Self::SerialBusController_USB_UsbDevice,
            (0x0c, 0x03, unk_i) => Self::SerialBusController_USB_Unknown(unk_i),
            (0x0c, 0x04, 0x00) => Self::SerialBusController_FibreChannel_Default,
            (0x0c, 0x04, unk_i) => Self::SerialBusController_FibreChannel_Unknown(unk_i),
            (0x0c, 0x05, 0x00) => Self::SerialBusController_SystemManagementBus_Default,
            (0x0c, 0x05, unk_i) => Self::SerialBusController_SystemManagementBus_Unknown(unk_i),
            (0x0c, 0x06, 0x00) => Self::SerialBusController_InfiniBandDeprecated_Default,
            (0x0c, 0x06, unk_i) => Self::SerialBusController_InfiniBandDeprecated_Unknown(unk_i),
            (0x0c, 0x07, 0x00) => Self::SerialBusController_Ipmi_Smic,
            (0x0c, 0x07, 0x01) => Self::SerialBusController_Ipmi_KeyboardControllerStyle,
            (0x0c, 0x07, 0x02) => Self::SerialBusController_Ipmi_BlockTransferInterface,
            (0x0c, 0x07, unk_i) => Self::SerialBusController_Ipmi_Unknown(unk_i),
            (0x0c, 0x08, 0x00) => Self::SerialBusController_SERCOS_Default,
            (0x0c, 0x08, unk_i) => Self::SerialBusController_SERCOS_Unknown(unk_i),
            (0x0c, 0x09, 0x00) => Self::SerialBusController_CANbus_Default,
            (0x0c, 0x09, unk_i) => Self::SerialBusController_CANbus_Unknown(unk_i),
            (0x0c, 0x0a, 0x00) => Self::SerialBusController_MipiI3C_Default,
            (0x0c, 0x0a, unk_i) => Self::SerialBusController_MipiI3C_Unknown(unk_i),
            (0x0c, 0x80, 0x00) => Self::SerialBusController_Other_VendorSpecific,
            (0x0c, 0x80, unk_i) => Self::SerialBusController_Other_Unknown(unk_i),
            (0x0c, unk_s, unk_i) => Self::SerialBusController_Unknown(unk_s, unk_i),
            (0x0d, 0x00, 0x00) => Self::WirelessController_iRDA_Default,
            (0x0d, 0x00, unk_i) => Self::WirelessController_iRDA_Unknown(unk_i),
            (0x0d, 0x01, 0x00) => Self::WirelessController_Radio_ConsumerIR,
            (0x0d, 0x01, 0x10) => Self::WirelessController_Radio_UWB,
            (0x0d, 0x01, unk_i) => Self::WirelessController_Radio_Unknown(unk_i),
            (0x0d, 0x10, 0x00) => Self::WirelessController_RFController_Default,
            (0x0d, 0x10, unk_i) => Self::WirelessController_RFController_Unknown(unk_i),
            (0x0d, 0x11, 0x00) => Self::WirelessController_Bluetooth_Default,
            (0x0d, 0x11, unk_i) => Self::WirelessController_Bluetooth_Unknown(unk_i),
            (0x0d, 0x12, 0x00) => Self::WirelessController_Broadband_Default,
            (0x0d, 0x12, unk_i) => Self::WirelessController_Broadband_Unknown(unk_i),
            (0x0d, 0x20, 0x00) => Self::WirelessController_Wifi802_11A_Default,
            (0x0d, 0x20, unk_i) => Self::WirelessController_Wifi802_11A_Unknown(unk_i),
            (0x0d, 0x21, 0x00) => Self::WirelessController_Wifi802_11B_Default,
            (0x0d, 0x21, unk_i) => Self::WirelessController_Wifi802_11B_Unknown(unk_i),
            (0x0d, 0x40, 0x00) => Self::WirelessController_CellularController_Default,
            (0x0d, 0x40, unk_i) => Self::WirelessController_CellularController_Unknown(unk_i),
            (0x0d, 0x41, 0x00) => Self::WirelessController_CellularControllerWithEthernet_Default,
            (0x0d, 0x41, unk_i) => Self::WirelessController_CellularControllerWithEthernet_Unknown(unk_i),
            (0x0d, 0x80, 0x00) => Self::WirelessController_Other_VendorSpecific,
            (0x0d, 0x80, unk_i) => Self::WirelessController_Other_Unknown(unk_i),
            (0x0d, unk_s, unk_i) => Self::WirelessController_Unknown(unk_s, unk_i),
            (0x0e, 0x00, 0x00) => Self::IntelligentIoController_IntelligentIoController_VendorSpecific,
            (0x0e, 0x00, unk_i) => Self::IntelligentIoController_IntelligentIoController_Unknown(unk_i),
            (0x0e, unk_s, unk_i) => Self::IntelligentIoController_Unknown(unk_s, unk_i),
            (0x0f, 0x01, 0x00) => Self::SatelliteCommController_Tv_VendorSpecific,
            (0x0f, 0x01, unk_i) => Self::SatelliteCommController_Tv_Unknown(unk_i),
            (0x0f, 0x02, 0x00) => Self::SatelliteCommController_Audio_VendorSpecific,
            (0x0f, 0x02, unk_i) => Self::SatelliteCommController_Audio_Unknown(unk_i),
            (0x0f, 0x03, 0x00) => Self::SatelliteCommController_Voice_VendorSpecific,
            (0x0f, 0x03, unk_i) => Self::SatelliteCommController_Voice_Unknown(unk_i),
            (0x0f, 0x04, 0x00) => Self::SatelliteCommController_Data_VendorSpecific,
            (0x0f, 0x04, unk_i) => Self::SatelliteCommController_Data_Unknown(unk_i),
            (0x0f, 0x80, 0x00) => Self::SatelliteCommController_Other_VendorSpecific,
            (0x0f, 0x80, unk_i) => Self::SatelliteCommController_Other_Unknown(unk_i),
            (0x0f, unk_s, unk_i) => Self::SatelliteCommController_Unknown(unk_s, unk_i),
            (0x10, 0x00, 0x00) => Self::EncryptionController_NetworkandComputingEncrpytionDecryption_VendorSpecific,
            (0x10, 0x00, unk_i) => Self::EncryptionController_NetworkandComputingEncrpytionDecryption_Unknown(unk_i),
            (0x10, 0x10, 0x00) => Self::EncryptionController_EntertainmentEncryptionDecryption_VendorSpecific,
            (0x10, 0x10, unk_i) => Self::EncryptionController_EntertainmentEncryptionDecryption_Unknown(unk_i),
            (0x10, 0x80, 0x00) => Self::EncryptionController_Other_VendorSpecific,
            (0x10, 0x80, unk_i) => Self::EncryptionController_Other_Unknown(unk_i),
            (0x10, unk_s, unk_i) => Self::EncryptionController_Unknown(unk_s, unk_i),
            (0x11, 0x00, 0x00) => Self::SignalProcessingController_DpIoModule_VendorSpecific,
            (0x11, 0x00, unk_i) => Self::SignalProcessingController_DpIoModule_Unknown(unk_i),
            (0x11, 0x01, 0x00) => Self::SignalProcessingController_PerformanceCounters_VendorSpecific,
            (0x11, 0x01, unk_i) => Self::SignalProcessingController_PerformanceCounters_Unknown(unk_i),
            (0x11, 0x10, 0x00) => Self::SignalProcessingController_CommunicationSynchronization_VendorSpecific,
            (0x11, 0x10, unk_i) => Self::SignalProcessingController_CommunicationSynchronization_Unknown(unk_i),
            (0x11, 0x20, 0x00) => Self::SignalProcessingController_ManagementCard_VendorSpecific,
            (0x11, 0x20, unk_i) => Self::SignalProcessingController_ManagementCard_Unknown(unk_i),
            (0x11, 0x80, 0x00) => Self::SignalProcessingController_Other_VendorSpecific,
            (0x11, 0x80, unk_i) => Self::SignalProcessingController_Other_Unknown(unk_i),
            (0x11, unk_s, unk_i) => Self::SignalProcessingController_Unknown(unk_s, unk_i),
            (0x12, 0x00, 0x00) => Self::ProcessingAccelerator_VendorSpecific_VendorSpecific,
            (0x12, 0x00, unk_i) => Self::ProcessingAccelerator_VendorSpecific_Unknown(unk_i),
            (0x12, 0x01, 0x00) => Self::ProcessingAccelerator_SniaSdxiController_VendorSpecific,
            (0x12, 0x01, unk_i) => Self::ProcessingAccelerator_SniaSdxiController_Unknown(unk_i),
            (0x12, unk_s, unk_i) => Self::ProcessingAccelerator_Unknown(unk_s, unk_i),
            (0x13, 0x00, 0x00) => Self::NonEssentialInstrumentation_VendorSpecific_VendorSpecific,
            (0x13, 0x00, unk_i) => Self::NonEssentialInstrumentation_VendorSpecific_Unknown(unk_i),
            (0x13, unk_s, unk_i) => Self::NonEssentialInstrumentation_Unknown(unk_s, unk_i),
            (unk_c, unk_s, unk_i) => Self::Unknown(unk_c, unk_s, unk_i),
        }
    }

    /// Converts a `PciDeviceInterfaceFunc` object into the
    /// `class_code`, `subclass_code` and `interface_func` that it represents.
    pub fn as_codes(&self) -> (u8, u8, u8) {
        match self {
            Self::Unclassified_Generic_VendorSpecific => (0x00, 0x00, 0x00),
            Self::Unclassified_Generic_Unknown(unk_i) => (0x00, 0x00, *unk_i),
            Self::Unclassified_VgaCompatible_VendorSpecific => (0x00, 0x01, 0x00),
            Self::Unclassified_VgaCompatible_Unknown(unk_i) => (0x00, 0x01, *unk_i),
            Self::Unclassified_Unknown(unk_s, unk_i) => (0x00, *unk_s, *unk_i),
            Self::MassStorageController_Scsi_VendorSpecific => (0x01, 0x00, 0x00),
            Self::MassStorageController_Scsi_StorageDevice => (0x01, 0x00, 0x11),
            Self::MassStorageController_Scsi_HostBusAdapter => (0x01, 0x00, 0x12),
            Self::MassStorageController_Scsi_StorageDeviceAndController => (0x01, 0x00, 0x13),
            Self::MassStorageController_Scsi_StorageDeviceOverPciE => (0x01, 0x00, 0x21),
            Self::MassStorageController_Scsi_Unknown(unk_i) => (0x01, 0x00, *unk_i),
            Self::MassStorageController_Ide_AtaInterface(if_code) => (0x01, 0x01, *if_code),
            Self::MassStorageController_FloppyDisk_VendorSpecific => (0x01, 0x02, 0x00),
            Self::MassStorageController_FloppyDisk_Unknown(unk_i) => (0x01, 0x02, *unk_i),
            Self::MassStorageController_IpiBus_VendorSpecific => (0x01, 0x03, 0x00),
            Self::MassStorageController_IpiBus_Unknown(unk_i) => (0x01, 0x03, *unk_i),
            Self::MassStorageController_Raid_VendorSpecific => (0x01, 0x04, 0x00),
            Self::MassStorageController_Raid_Unknown(unk_i) => (0x01, 0x04, *unk_i),
            Self::MassStorageController_AtaWithAdma_SingleStepping => (0x01, 0x05, 0x20),
            Self::MassStorageController_AtaWithAdma_ContinuousOperation => (0x01, 0x05, 0x30),
            Self::MassStorageController_AtaWithAdma_Unknown(unk_i) => (0x01, 0x05, *unk_i),
            Self::MassStorageController_SerialAta_VendorSpecific => (0x01, 0x06, 0x00),
            Self::MassStorageController_SerialAta_Ahci => (0x01, 0x06, 0x01),
            Self::MassStorageController_SerialAta_SerialStorageBus => (0x01, 0x06, 0x02),
            Self::MassStorageController_SerialAta_Unknown(unk_i) => (0x01, 0x06, *unk_i),
            Self::MassStorageController_SerialAttachedScsi_VendorSpecific => (0x01, 0x07, 0x00),
            Self::MassStorageController_SerialAttachedScsi_Obsolete => (0x01, 0x07, 0x01),
            Self::MassStorageController_SerialAttachedScsi_Unknown(unk_i) => (0x01, 0x07, *unk_i),
            Self::MassStorageController_NonVolatileMemory_VendorSpecific => (0x01, 0x08, 0x00),
            Self::MassStorageController_NonVolatileMemory_NvmHci => (0x01, 0x08, 0x01),
            Self::MassStorageController_NonVolatileMemory_NVMeIoController => (0x01, 0x08, 0x02),
            Self::MassStorageController_NonVolatileMemory_NVMeAdministrativeController => (0x01, 0x08, 0x03),
            Self::MassStorageController_NonVolatileMemory_Unknown(unk_i) => (0x01, 0x08, *unk_i),
            Self::MassStorageController_UniversalFlashStorage_VendorSpecific => (0x01, 0x09, 0x00),
            Self::MassStorageController_UniversalFlashStorage_UfsHci => (0x01, 0x09, 0x01),
            Self::MassStorageController_UniversalFlashStorage_Unknown(unk_i) => (0x01, 0x09, *unk_i),
            Self::MassStorageController_Other_VendorSpecific => (0x01, 0x80, 0x00),
            Self::MassStorageController_Other_Unknown(unk_i) => (0x01, 0x80, *unk_i),
            Self::MassStorageController_Unknown(unk_s, unk_i) => (0x01, *unk_s, *unk_i),
            Self::NetworkController_Ethernet_Default => (0x02, 0x00, 0x00),
            Self::NetworkController_Ethernet_Unknown(unk_i) => (0x02, 0x00, *unk_i),
            Self::NetworkController_TokenRing_Default => (0x02, 0x01, 0x00),
            Self::NetworkController_TokenRing_Unknown(unk_i) => (0x02, 0x01, *unk_i),
            Self::NetworkController_Fddi_Default => (0x02, 0x02, 0x00),
            Self::NetworkController_Fddi_Unknown(unk_i) => (0x02, 0x02, *unk_i),
            Self::NetworkController_Atm_Default => (0x02, 0x03, 0x00),
            Self::NetworkController_Atm_Unknown(unk_i) => (0x02, 0x03, *unk_i),
            Self::NetworkController_Isdn_Default => (0x02, 0x04, 0x00),
            Self::NetworkController_Isdn_Unknown(unk_i) => (0x02, 0x04, *unk_i),
            Self::NetworkController_WorldFip_Default => (0x02, 0x05, 0x00),
            Self::NetworkController_WorldFip_Unknown(unk_i) => (0x02, 0x05, *unk_i),
            Self::NetworkController_PicMg214MultiComputing_PicMg(if_code) => (0x02, 0x06, *if_code),
            Self::NetworkController_InfiniBand_Default => (0x02, 0x07, 0x00),
            Self::NetworkController_InfiniBand_Unknown(unk_i) => (0x02, 0x07, *unk_i),
            Self::NetworkController_Other_VendorSpecific => (0x02, 0x80, 0x00),
            Self::NetworkController_Other_Unknown(unk_i) => (0x02, 0x80, *unk_i),
            Self::NetworkController_Unknown(unk_s, unk_i) => (0x02, *unk_s, *unk_i),
            Self::DisplayController_VgaCompatible_Vga => (0x03, 0x00, 0x00),
            Self::DisplayController_VgaCompatible_Ibm8514 => (0x03, 0x00, 0x01),
            Self::DisplayController_VgaCompatible_Unknown(unk_i) => (0x03, 0x00, *unk_i),
            Self::DisplayController_Xga_Default => (0x03, 0x01, 0x00),
            Self::DisplayController_Xga_Unknown(unk_i) => (0x03, 0x01, *unk_i),
            Self::DisplayController_NonVga3D_VendorSpecific => (0x03, 0x02, 0x00),
            Self::DisplayController_NonVga3D_Unknown(unk_i) => (0x03, 0x02, *unk_i),
            Self::DisplayController_Other_VendorSpecific => (0x03, 0x80, 0x00),
            Self::DisplayController_Other_Unknown(unk_i) => (0x03, 0x80, *unk_i),
            Self::DisplayController_Unknown(unk_s, unk_i) => (0x03, *unk_s, *unk_i),
            Self::MultimediaDevice_VideoDevice_VendorSpecific => (0x04, 0x00, 0x00),
            Self::MultimediaDevice_VideoDevice_Unknown(unk_i) => (0x04, 0x00, *unk_i),
            Self::MultimediaDevice_AudioDevice_VendorSpecific => (0x04, 0x01, 0x00),
            Self::MultimediaDevice_AudioDevice_Unknown(unk_i) => (0x04, 0x01, *unk_i),
            Self::MultimediaDevice_ComputerTelephony_VendorSpecific => (0x04, 0x02, 0x00),
            Self::MultimediaDevice_ComputerTelephony_Unknown(unk_i) => (0x04, 0x02, *unk_i),
            Self::MultimediaDevice_HdaCompatible_HighDefinitionAudio => (0x04, 0x03, 0x00),
            Self::MultimediaDevice_HdaCompatible_HighDefinitionAudioWithVendorExtension => (0x04, 0x03, 0x80),
            Self::MultimediaDevice_HdaCompatible_Unknown(unk_i) => (0x04, 0x03, *unk_i),
            Self::MultimediaDevice_Other_VendorSpecific => (0x04, 0x80, 0x00),
            Self::MultimediaDevice_Other_Unknown(unk_i) => (0x04, 0x80, *unk_i),
            Self::MultimediaDevice_Unknown(unk_s, unk_i) => (0x04, *unk_s, *unk_i),
            Self::MemoryController_Ram_Default => (0x05, 0x00, 0x00),
            Self::MemoryController_Ram_Unknown(unk_i) => (0x05, 0x00, *unk_i),
            Self::MemoryController_Flash_Default => (0x05, 0x01, 0x00),
            Self::MemoryController_Flash_Unknown(unk_i) => (0x05, 0x01, *unk_i),
            Self::MemoryController_CxlMemory_VendorSpecific => (0x05, 0x02, 0x00),
            Self::MemoryController_CxlMemory_Cxl2Specifications => (0x05, 0x02, 0x10),
            Self::MemoryController_CxlMemory_Unknown(unk_i) => (0x05, 0x02, *unk_i),
            Self::MemoryController_Other_VendorSpecific => (0x05, 0x80, 0x00),
            Self::MemoryController_Other_Unknown(unk_i) => (0x05, 0x80, *unk_i),
            Self::MemoryController_Unknown(unk_s, unk_i) => (0x05, *unk_s, *unk_i),
            Self::Bridge_HostBridge_Default => (0x06, 0x00, 0x00),
            Self::Bridge_HostBridge_Unknown(unk_i) => (0x06, 0x00, *unk_i),
            Self::Bridge_IsaBridge_Default => (0x06, 0x01, 0x00),
            Self::Bridge_IsaBridge_Unknown(unk_i) => (0x06, 0x01, *unk_i),
            Self::Bridge_EisaBridge_Default => (0x06, 0x02, 0x00),
            Self::Bridge_EisaBridge_Unknown(unk_i) => (0x06, 0x02, *unk_i),
            Self::Bridge_McaBridge_Default => (0x06, 0x03, 0x00),
            Self::Bridge_McaBridge_Unknown(unk_i) => (0x06, 0x03, *unk_i),
            Self::Bridge_PciToPciBridge_PciToPci => (0x06, 0x04, 0x00),
            Self::Bridge_PciToPciBridge_SubtractiveDecodePciToPci => (0x06, 0x04, 0x01),
            Self::Bridge_PciToPciBridge_Unknown(unk_i) => (0x06, 0x04, *unk_i),
            Self::Bridge_PcmciaBridge_Default => (0x06, 0x05, 0x00),
            Self::Bridge_PcmciaBridge_Unknown(unk_i) => (0x06, 0x05, *unk_i),
            Self::Bridge_NuBusBridge_Default => (0x06, 0x06, 0x00),
            Self::Bridge_NuBusBridge_Unknown(unk_i) => (0x06, 0x06, *unk_i),
            Self::Bridge_CardBusBridge_Default => (0x06, 0x07, 0x00),
            Self::Bridge_CardBusBridge_Unknown(unk_i) => (0x06, 0x07, *unk_i),
            Self::Bridge_RacewayBridge_Default => (0x06, 0x08, 0x00),
            Self::Bridge_RacewayBridge_Unknown(unk_i) => (0x06, 0x08, *unk_i),
            Self::Bridge_SemiTransparentPciToPciBridge_Primary => (0x06, 0x09, 0x40),
            Self::Bridge_SemiTransparentPciToPciBridge_Secondary => (0x06, 0x09, 0x80),
            Self::Bridge_SemiTransparentPciToPciBridge_Unknown(unk_i) => (0x06, 0x09, *unk_i),
            Self::Bridge_InfiniBandtoPciHostBridge_Default => (0x06, 0x0a, 0x00),
            Self::Bridge_InfiniBandtoPciHostBridge_Unknown(unk_i) => (0x06, 0x0a, *unk_i),
            Self::Bridge_AdvancedSwitchingToPciHostBridge_VendorSpecific => (0x06, 0x0b, 0x00),
            Self::Bridge_AdvancedSwitchingToPciHostBridge_AsiSigInterface => (0x06, 0x0b, 0x01),
            Self::Bridge_AdvancedSwitchingToPciHostBridge_Unknown(unk_i) => (0x06, 0x0b, *unk_i),
            Self::Bridge_Other_VendorSpecific => (0x06, 0x80, 0x00),
            Self::Bridge_Other_Unknown(unk_i) => (0x06, 0x80, *unk_i),
            Self::Bridge_Unknown(unk_s, unk_i) => (0x06, *unk_s, *unk_i),
            Self::CommunicationController_Serial_Uart8250 => (0x07, 0x00, 0x00),
            Self::CommunicationController_Serial_Uart16450 => (0x07, 0x00, 0x01),
            Self::CommunicationController_Serial_Uart16550 => (0x07, 0x00, 0x02),
            Self::CommunicationController_Serial_Uart16650 => (0x07, 0x00, 0x03),
            Self::CommunicationController_Serial_Uart16750 => (0x07, 0x00, 0x04),
            Self::CommunicationController_Serial_Uart16850 => (0x07, 0x00, 0x05),
            Self::CommunicationController_Serial_Uart16950 => (0x07, 0x00, 0x06),
            Self::CommunicationController_Serial_Unknown(unk_i) => (0x07, 0x00, *unk_i),
            Self::CommunicationController_Parallel_ParallelPort => (0x07, 0x01, 0x00),
            Self::CommunicationController_Parallel_BidirectionalParallelPort => (0x07, 0x01, 0x01),
            Self::CommunicationController_Parallel_EcpParallelPort => (0x07, 0x01, 0x02),
            Self::CommunicationController_Parallel_Ieee1284Controller => (0x07, 0x01, 0x03),
            Self::CommunicationController_Parallel_Ieee1284TargetDevice => (0x07, 0x01, 0xfe),
            Self::CommunicationController_Parallel_Unknown(unk_i) => (0x07, 0x01, *unk_i),
            Self::CommunicationController_MultiportSerialController_Default => (0x07, 0x02, 0x00),
            Self::CommunicationController_MultiportSerialController_Unknown(unk_i) => (0x07, 0x02, *unk_i),
            Self::CommunicationController_Modem_Generic => (0x07, 0x03, 0x00),
            Self::CommunicationController_Modem_Hayes16450Compatible => (0x07, 0x03, 0x01),
            Self::CommunicationController_Modem_Hayes16550Compatible => (0x07, 0x03, 0x02),
            Self::CommunicationController_Modem_Hayes16650Compatible => (0x07, 0x03, 0x03),
            Self::CommunicationController_Modem_Hayes16750Compatible => (0x07, 0x03, 0x04),
            Self::CommunicationController_Modem_Unknown(unk_i) => (0x07, 0x03, *unk_i),
            Self::CommunicationController_GpibController_Default => (0x07, 0x04, 0x00),
            Self::CommunicationController_GpibController_Unknown(unk_i) => (0x07, 0x04, *unk_i),
            Self::CommunicationController_Smartcard_Default => (0x07, 0x05, 0x00),
            Self::CommunicationController_Smartcard_Unknown(unk_i) => (0x07, 0x05, *unk_i),
            Self::CommunicationController_Other_VendorSpecific => (0x07, 0x80, 0x00),
            Self::CommunicationController_Other_Unknown(unk_i) => (0x07, 0x80, *unk_i),
            Self::CommunicationController_Unknown(unk_s, unk_i) => (0x07, *unk_s, *unk_i),
            Self::BaseSystemPeripheral_PIC_Generic8259 => (0x08, 0x00, 0x00),
            Self::BaseSystemPeripheral_PIC_Isa => (0x08, 0x00, 0x01),
            Self::BaseSystemPeripheral_PIC_Eisa => (0x08, 0x00, 0x02),
            Self::BaseSystemPeripheral_PIC_IoApic => (0x08, 0x00, 0x10),
            Self::BaseSystemPeripheral_PIC_IoXApic => (0x08, 0x00, 0x20),
            Self::BaseSystemPeripheral_PIC_Unknown(unk_i) => (0x08, 0x00, *unk_i),
            Self::BaseSystemPeripheral_DmaController_Generic8237 => (0x08, 0x01, 0x00),
            Self::BaseSystemPeripheral_DmaController_Isa => (0x08, 0x01, 0x01),
            Self::BaseSystemPeripheral_DmaController_Eisa => (0x08, 0x01, 0x02),
            Self::BaseSystemPeripheral_DmaController_Unknown(unk_i) => (0x08, 0x01, *unk_i),
            Self::BaseSystemPeripheral_SystemTimer_Generic8254 => (0x08, 0x02, 0x00),
            Self::BaseSystemPeripheral_SystemTimer_Isa => (0x08, 0x02, 0x01),
            Self::BaseSystemPeripheral_SystemTimer_Eisa => (0x08, 0x02, 0x02),
            Self::BaseSystemPeripheral_SystemTimer_HighPerformanceEventTimer => (0x08, 0x02, 0x03),
            Self::BaseSystemPeripheral_SystemTimer_Unknown(unk_i) => (0x08, 0x02, *unk_i),
            Self::BaseSystemPeripheral_RealTimeClockController_GenericRtc => (0x08, 0x03, 0x00),
            Self::BaseSystemPeripheral_RealTimeClockController_Isa => (0x08, 0x03, 0x01),
            Self::BaseSystemPeripheral_RealTimeClockController_Unknown(unk_i) => (0x08, 0x03, *unk_i),
            Self::BaseSystemPeripheral_GenericPciHotPlugController_Default => (0x08, 0x04, 0x00),
            Self::BaseSystemPeripheral_GenericPciHotPlugController_Unknown(unk_i) => (0x08, 0x04, *unk_i),
            Self::BaseSystemPeripheral_SdHostController_Default => (0x08, 0x05, 0x00),
            Self::BaseSystemPeripheral_SdHostController_Unknown(unk_i) => (0x08, 0x05, *unk_i),
            Self::BaseSystemPeripheral_IOMMU_Default => (0x08, 0x06, 0x00),
            Self::BaseSystemPeripheral_IOMMU_Unknown(unk_i) => (0x08, 0x06, *unk_i),
            Self::BaseSystemPeripheral_RootComplexEventCollector_Default => (0x08, 0x07, 0x00),
            Self::BaseSystemPeripheral_RootComplexEventCollector_Unknown(unk_i) => (0x08, 0x07, *unk_i),
            Self::BaseSystemPeripheral_Other_VendorSpecific => (0x08, 0x80, 0x00),
            Self::BaseSystemPeripheral_Other_Unknown(unk_i) => (0x08, 0x80, *unk_i),
            Self::BaseSystemPeripheral_Unknown(unk_s, unk_i) => (0x08, *unk_s, *unk_i),
            Self::InputDevice_KeyboardController_Default => (0x09, 0x00, 0x00),
            Self::InputDevice_KeyboardController_Unknown(unk_i) => (0x09, 0x00, *unk_i),
            Self::InputDevice_DigitizerPenController_Default => (0x09, 0x01, 0x00),
            Self::InputDevice_DigitizerPenController_Unknown(unk_i) => (0x09, 0x01, *unk_i),
            Self::InputDevice_MouseController_Default => (0x09, 0x02, 0x00),
            Self::InputDevice_MouseController_Unknown(unk_i) => (0x09, 0x02, *unk_i),
            Self::InputDevice_ScannerController_Default => (0x09, 0x03, 0x00),
            Self::InputDevice_ScannerController_Unknown(unk_i) => (0x09, 0x03, *unk_i),
            Self::InputDevice_GameportController_Generic => (0x09, 0x04, 0x00),
            Self::InputDevice_GameportController_LegacyGamePort => (0x09, 0x04, 0x10),
            Self::InputDevice_GameportController_Unknown(unk_i) => (0x09, 0x04, *unk_i),
            Self::InputDevice_Other_VendorSpecific => (0x09, 0x80, 0x00),
            Self::InputDevice_Other_Unknown(unk_i) => (0x09, 0x80, *unk_i),
            Self::InputDevice_Unknown(unk_s, unk_i) => (0x09, *unk_s, *unk_i),
            Self::DockingStation_Generic_VendorSpecific => (0x0a, 0x00, 0x00),
            Self::DockingStation_Generic_Unknown(unk_i) => (0x0a, 0x00, *unk_i),
            Self::DockingStation_Other_VendorSpecific => (0x0a, 0x80, 0x00),
            Self::DockingStation_Other_Unknown(unk_i) => (0x0a, 0x80, *unk_i),
            Self::DockingStation_Unknown(unk_s, unk_i) => (0x0a, *unk_s, *unk_i),
            Self::Processor_Intel386_VendorSpecific => (0x0b, 0x00, 0x00),
            Self::Processor_Intel386_Unknown(unk_i) => (0x0b, 0x00, *unk_i),
            Self::Processor_Intel486_VendorSpecific => (0x0b, 0x01, 0x00),
            Self::Processor_Intel486_Unknown(unk_i) => (0x0b, 0x01, *unk_i),
            Self::Processor_IntelPentium_VendorSpecific => (0x0b, 0x02, 0x00),
            Self::Processor_IntelPentium_Unknown(unk_i) => (0x0b, 0x02, *unk_i),
            Self::Processor_DecAlpha_VendorSpecific => (0x0b, 0x10, 0x00),
            Self::Processor_DecAlpha_Unknown(unk_i) => (0x0b, 0x10, *unk_i),
            Self::Processor_PowerPc_VendorSpecific => (0x0b, 0x20, 0x00),
            Self::Processor_PowerPc_Unknown(unk_i) => (0x0b, 0x20, *unk_i),
            Self::Processor_Mips_VendorSpecific => (0x0b, 0x30, 0x00),
            Self::Processor_Mips_Unknown(unk_i) => (0x0b, 0x30, *unk_i),
            Self::Processor_Coprocessor_VendorSpecific => (0x0b, 0x40, 0x00),
            Self::Processor_Coprocessor_Unknown(unk_i) => (0x0b, 0x40, *unk_i),
            Self::Processor_Other_VendorSpecific => (0x0b, 0x80, 0x00),
            Self::Processor_Other_Unknown(unk_i) => (0x0b, 0x80, *unk_i),
            Self::Processor_Unknown(unk_s, unk_i) => (0x0b, *unk_s, *unk_i),
            Self::SerialBusController_Ieee1394_FireWire => (0x0c, 0x00, 0x00),
            Self::SerialBusController_Ieee1394_Ieee1394OpenHCI => (0x0c, 0x00, 0x10),
            Self::SerialBusController_Ieee1394_Unknown(unk_i) => (0x0c, 0x00, *unk_i),
            Self::SerialBusController_ACCESSbus_Default => (0x0c, 0x01, 0x00),
            Self::SerialBusController_ACCESSbus_Unknown(unk_i) => (0x0c, 0x01, *unk_i),
            Self::SerialBusController_SSA_Default => (0x0c, 0x02, 0x00),
            Self::SerialBusController_SSA_Unknown(unk_i) => (0x0c, 0x02, *unk_i),
            Self::SerialBusController_USB_UhcsController => (0x0c, 0x03, 0x00),
            Self::SerialBusController_USB_OhcsController => (0x0c, 0x03, 0x10),
            Self::SerialBusController_USB_Usb2Ehci => (0x0c, 0x03, 0x20),
            Self::SerialBusController_USB_Usb3Xhci => (0x0c, 0x03, 0x30),
            Self::SerialBusController_USB_Usb4HostInterface => (0x0c, 0x03, 0x40),
            Self::SerialBusController_USB_UsbGeneric => (0x0c, 0x03, 0x80),
            Self::SerialBusController_USB_UsbDevice => (0x0c, 0x03, 0xfe),
            Self::SerialBusController_USB_Unknown(unk_i) => (0x0c, 0x03, *unk_i),
            Self::SerialBusController_FibreChannel_Default => (0x0c, 0x04, 0x00),
            Self::SerialBusController_FibreChannel_Unknown(unk_i) => (0x0c, 0x04, *unk_i),
            Self::SerialBusController_SystemManagementBus_Default => (0x0c, 0x05, 0x00),
            Self::SerialBusController_SystemManagementBus_Unknown(unk_i) => (0x0c, 0x05, *unk_i),
            Self::SerialBusController_InfiniBandDeprecated_Default => (0x0c, 0x06, 0x00),
            Self::SerialBusController_InfiniBandDeprecated_Unknown(unk_i) => (0x0c, 0x06, *unk_i),
            Self::SerialBusController_Ipmi_Smic => (0x0c, 0x07, 0x00),
            Self::SerialBusController_Ipmi_KeyboardControllerStyle => (0x0c, 0x07, 0x01),
            Self::SerialBusController_Ipmi_BlockTransferInterface => (0x0c, 0x07, 0x02),
            Self::SerialBusController_Ipmi_Unknown(unk_i) => (0x0c, 0x07, *unk_i),
            Self::SerialBusController_SERCOS_Default => (0x0c, 0x08, 0x00),
            Self::SerialBusController_SERCOS_Unknown(unk_i) => (0x0c, 0x08, *unk_i),
            Self::SerialBusController_CANbus_Default => (0x0c, 0x09, 0x00),
            Self::SerialBusController_CANbus_Unknown(unk_i) => (0x0c, 0x09, *unk_i),
            Self::SerialBusController_MipiI3C_Default => (0x0c, 0x0a, 0x00),
            Self::SerialBusController_MipiI3C_Unknown(unk_i) => (0x0c, 0x0a, *unk_i),
            Self::SerialBusController_Other_VendorSpecific => (0x0c, 0x80, 0x00),
            Self::SerialBusController_Other_Unknown(unk_i) => (0x0c, 0x80, *unk_i),
            Self::SerialBusController_Unknown(unk_s, unk_i) => (0x0c, *unk_s, *unk_i),
            Self::WirelessController_iRDA_Default => (0x0d, 0x00, 0x00),
            Self::WirelessController_iRDA_Unknown(unk_i) => (0x0d, 0x00, *unk_i),
            Self::WirelessController_Radio_ConsumerIR => (0x0d, 0x01, 0x00),
            Self::WirelessController_Radio_UWB => (0x0d, 0x01, 0x10),
            Self::WirelessController_Radio_Unknown(unk_i) => (0x0d, 0x01, *unk_i),
            Self::WirelessController_RFController_Default => (0x0d, 0x10, 0x00),
            Self::WirelessController_RFController_Unknown(unk_i) => (0x0d, 0x10, *unk_i),
            Self::WirelessController_Bluetooth_Default => (0x0d, 0x11, 0x00),
            Self::WirelessController_Bluetooth_Unknown(unk_i) => (0x0d, 0x11, *unk_i),
            Self::WirelessController_Broadband_Default => (0x0d, 0x12, 0x00),
            Self::WirelessController_Broadband_Unknown(unk_i) => (0x0d, 0x12, *unk_i),
            Self::WirelessController_Wifi802_11A_Default => (0x0d, 0x20, 0x00),
            Self::WirelessController_Wifi802_11A_Unknown(unk_i) => (0x0d, 0x20, *unk_i),
            Self::WirelessController_Wifi802_11B_Default => (0x0d, 0x21, 0x00),
            Self::WirelessController_Wifi802_11B_Unknown(unk_i) => (0x0d, 0x21, *unk_i),
            Self::WirelessController_CellularController_Default => (0x0d, 0x40, 0x00),
            Self::WirelessController_CellularController_Unknown(unk_i) => (0x0d, 0x40, *unk_i),
            Self::WirelessController_CellularControllerWithEthernet_Default => (0x0d, 0x41, 0x00),
            Self::WirelessController_CellularControllerWithEthernet_Unknown(unk_i) => (0x0d, 0x41, *unk_i),
            Self::WirelessController_Other_VendorSpecific => (0x0d, 0x80, 0x00),
            Self::WirelessController_Other_Unknown(unk_i) => (0x0d, 0x80, *unk_i),
            Self::WirelessController_Unknown(unk_s, unk_i) => (0x0d, *unk_s, *unk_i),
            Self::IntelligentIoController_IntelligentIoController_VendorSpecific => (0x0e, 0x00, 0x00),
            Self::IntelligentIoController_IntelligentIoController_Unknown(unk_i) => (0x0e, 0x00, *unk_i),
            Self::IntelligentIoController_Unknown(unk_s, unk_i) => (0x0e, *unk_s, *unk_i),
            Self::SatelliteCommController_Tv_VendorSpecific => (0x0f, 0x01, 0x00),
            Self::SatelliteCommController_Tv_Unknown(unk_i) => (0x0f, 0x01, *unk_i),
            Self::SatelliteCommController_Audio_VendorSpecific => (0x0f, 0x02, 0x00),
            Self::SatelliteCommController_Audio_Unknown(unk_i) => (0x0f, 0x02, *unk_i),
            Self::SatelliteCommController_Voice_VendorSpecific => (0x0f, 0x03, 0x00),
            Self::SatelliteCommController_Voice_Unknown(unk_i) => (0x0f, 0x03, *unk_i),
            Self::SatelliteCommController_Data_VendorSpecific => (0x0f, 0x04, 0x00),
            Self::SatelliteCommController_Data_Unknown(unk_i) => (0x0f, 0x04, *unk_i),
            Self::SatelliteCommController_Other_VendorSpecific => (0x0f, 0x80, 0x00),
            Self::SatelliteCommController_Other_Unknown(unk_i) => (0x0f, 0x80, *unk_i),
            Self::SatelliteCommController_Unknown(unk_s, unk_i) => (0x0f, *unk_s, *unk_i),
            Self::EncryptionController_NetworkandComputingEncrpytionDecryption_VendorSpecific => (0x10, 0x00, 0x00),
            Self::EncryptionController_NetworkandComputingEncrpytionDecryption_Unknown(unk_i) => (0x10, 0x00, *unk_i),
            Self::EncryptionController_EntertainmentEncryptionDecryption_VendorSpecific => (0x10, 0x10, 0x00),
            Self::EncryptionController_EntertainmentEncryptionDecryption_Unknown(unk_i) => (0x10, 0x10, *unk_i),
            Self::EncryptionController_Other_VendorSpecific => (0x10, 0x80, 0x00),
            Self::EncryptionController_Other_Unknown(unk_i) => (0x10, 0x80, *unk_i),
            Self::EncryptionController_Unknown(unk_s, unk_i) => (0x10, *unk_s, *unk_i),
            Self::SignalProcessingController_DpIoModule_VendorSpecific => (0x11, 0x00, 0x00),
            Self::SignalProcessingController_DpIoModule_Unknown(unk_i) => (0x11, 0x00, *unk_i),
            Self::SignalProcessingController_PerformanceCounters_VendorSpecific => (0x11, 0x01, 0x00),
            Self::SignalProcessingController_PerformanceCounters_Unknown(unk_i) => (0x11, 0x01, *unk_i),
            Self::SignalProcessingController_CommunicationSynchronization_VendorSpecific => (0x11, 0x10, 0x00),
            Self::SignalProcessingController_CommunicationSynchronization_Unknown(unk_i) => (0x11, 0x10, *unk_i),
            Self::SignalProcessingController_ManagementCard_VendorSpecific => (0x11, 0x20, 0x00),
            Self::SignalProcessingController_ManagementCard_Unknown(unk_i) => (0x11, 0x20, *unk_i),
            Self::SignalProcessingController_Other_VendorSpecific => (0x11, 0x80, 0x00),
            Self::SignalProcessingController_Other_Unknown(unk_i) => (0x11, 0x80, *unk_i),
            Self::SignalProcessingController_Unknown(unk_s, unk_i) => (0x11, *unk_s, *unk_i),
            Self::ProcessingAccelerator_VendorSpecific_VendorSpecific => (0x12, 0x00, 0x00),
            Self::ProcessingAccelerator_VendorSpecific_Unknown(unk_i) => (0x12, 0x00, *unk_i),
            Self::ProcessingAccelerator_SniaSdxiController_VendorSpecific => (0x12, 0x01, 0x00),
            Self::ProcessingAccelerator_SniaSdxiController_Unknown(unk_i) => (0x12, 0x01, *unk_i),
            Self::ProcessingAccelerator_Unknown(unk_s, unk_i) => (0x12, *unk_s, *unk_i),
            Self::NonEssentialInstrumentation_VendorSpecific_VendorSpecific => (0x13, 0x00, 0x00),
            Self::NonEssentialInstrumentation_VendorSpecific_Unknown(unk_i) => (0x13, 0x00, *unk_i),
            Self::NonEssentialInstrumentation_Unknown(unk_s, unk_i) => (0x13, *unk_s, *unk_i),
            Self::Unknown(unk_c, unk_s, unk_i) => (*unk_c, *unk_s, *unk_i),
        }
    }
}

impl From<PciDeviceInterfaceFunc> for u8 {
    fn from(value: PciDeviceInterfaceFunc) -> Self {
        value.as_codes().2
    }
}

#[cfg(not(feature = "pci_interface_func_debug_strings"))]
impl std::fmt::Debug for PciDeviceInterfaceFunc {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let v = self.as_codes();
        write!(f, "(clss:{:02X}h subc:{:02X}h if:{:02X}h)", v.0, v.1, v.2)
    }
}


